In [8]:
import pandas as pd

df = pd.read_csv("retail_store_inventory.csv")
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  object
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  object
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 8.4+ MB

In [11]:
df=df.drop(columns=['Seasonality','Weather Condition','Holiday/Promotion'])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  object
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Competitor Pricing  73100 non-null  float64
dtypes: float64(3), int64(4), object(5)
memory usage: 6.7+ MB

In [13]:
df = df.drop_duplicates()

In [14]:
df['Date'] = pd.to_datetime(df['Date'])

In [15]:
df.dtypes

Date                  datetime64[ns]
Store ID                      object
Product ID                    object
Category                      object
Region                        object
Inventory Level                int64
Units Sold                     int64
Units Ordered                  int64
Demand Forecast              float64
Price                        float64
Discount                       int64
Competitor Pricing           float64
dtype: object

In [16]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Competitor Pricing
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,29.69
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,66.16
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,31.32
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,34.74
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,68.95

In [17]:
df = df.dropna()

In [18]:
df.describe()

,Date,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Competitor Pricing
count,73100,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,2022-12-31 23:59:59.999999744,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,55.146077
min,2022-01-01 00:00:00,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,5.030000
25%,2022-07-02 00:00:00,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,32.680000
50%,2023-01-01 00:00:00,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,55.010000
75%,2023-07-03 00:00:00,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,77.820000
max,2024-01-01 00:00:00,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,104.940000
std,NaN,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,26.191408

In [19]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Competitor Pricing
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,29.69
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,66.16
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,31.32
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,34.74
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,68.95

In [20]:
product_sales = df.groupby('Product ID')['Units Sold'].sum().sort_values()

slow_products = product_sales.head(10)
fast_products = product_sales.tail(10)

print("Slow Moving Products:\n", slow_products)
print("\nFast Moving Products:\n", fast_products)

Slow Moving Products:
 Product ID
P0002    487827
P0008    488563
P0012    491670
P0018    492551
P0003    493279
P0004    495501
P0010    496469
P0006    497131
P0019    497899
P0001    498061
Name: Units Sold, dtype: int64

Fast Moving Products:
 Product ID
P0007    499321
P0011    499362
P0017    500510
P0013    500619
P0009    502086
P0005    503648
P0015    507283
P0014    507622
P0020    507708
P0016    508472
Name: Units Sold, dtype: int64

In [21]:
df['Stockout'] = df['Units Sold'] > df['Inventory Level']

stockout_count = df['Stockout'].value_counts()
print(stockout_count)

Stockout
False    73100
Name: count, dtype: int64

In [22]:
df['Overstock'] = df['Inventory Level'] > df['Units Sold'] * 2

overstock_count = df['Overstock'].value_counts()
print(overstock_count)

Overstock
True     36783
False    36317
Name: count, dtype: int64